import pandas as pd

configfile: "config/config.yaml"

read_scores = pd.read_table(config["read_scores"], header=0).set_index(["sample"], drop=False)

def get_reads(wildcards):
	return [read_scores["R1"][wildcards.sample], read_scores["R2"][wildcards.sample]]

def get_samples(wildcards):
	return read_scores["sample"][wildcards.sample]

rule all:
	input:
		expand("results/jellyfish/{sample}.jf", sample = read_scores["sample"])

rule jellyfish:
	input:
		get_reads
	output:
		jf="results/jellyfish/{sample}.jf"
	log:
		"logs/jellyfish/{sample}.log"
	threads:
		4
	resources:
		mem_mb=16000,
		partition="short"
	conda:
		"envs/jellyfish.yaml"
	shell:
		"""(zcat {input} | jellyfish count /dev/fd/0 -C -m 51 -s 1G -t 4 -o {output.jf}) > {log}"""

