read_scores: "config/read_scores.txt"
assembly: "config/vales_everest.contigs.fasta"
assembly_title: "Vales_Everest"
reference: "config/DM_1-3_516_R44_potato_genome_assembly.v6.1.fasta"
assoc_threshold: 25
